"use client";
/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- Labelled overflow regions must remain keyboard-scrollable. */
import {useMemo,useState} from "react";

const layers=[
 ["CUTLASS","Kütüphane","Üretim kalitesinde GEMM ve ilişkili işlemler için ayarlanabilir CUDA C++ şablonları."],
 ["CuTe","Layout cebiri","Shape + stride ile koordinat→adres eşlemesini, tensor bölümlemeyi, kopyalamayı ve MMA düzenini ifade eder."],
 ["PTX","Sanal ISA","Derleyici ile hedefe özel makine kodu arasında taşınabilir ara seviye talimat dili."],
 ["Tensor Core","Donanım","Küçük matris fragment’lerinde D=A×B+C işlemini yüksek verimle yapan özel hesap birimleri."],
];
const codes={
 CUTLASS:`using Gemm = cutlass::gemm::device::Gemm<\n  cutlass::half_t, RowMajor,\n  cutlass::half_t, ColumnMajor,\n  float, RowMajor\n>;\n\nGemm op;\nop({problem, A, B, C, D, alpha, beta});`,
 CuTe:`auto layout = make_layout(\n  make_shape(Int<128>{}, Int<64>{}),\n  make_stride(Int<1>{}, Int<128>{})\n);\n\nauto tensor = make_tensor(ptr, layout);\nauto tile = local_tile(tensor, tile_shape, coord);`,
 PTX:`mma.sync.aligned.m16n8k16\n  .row.col.f32.f16.f16.f32\n  {d0, d1, d2, d3},\n  {a0, a1, a2, a3},\n  {b0, b1},\n  {c0, c1, c2, c3};`,
 WMMA:`wmma::load_matrix_sync(a, A, lda);\nwmma::load_matrix_sync(b, B, ldb);\nwmma::mma_sync(c, a, b, c);\nwmma::store_matrix_sync(D, c, ldd,\n  wmma::mem_row_major);`,
};
const notes={CUTLASS:"Problemi ve politikaları tarif edersin; kütüphane mainloop, veri taşıma, MMA ve epilogue bileşenlerini toplar.",CuTe:"Layout yalnız boyut değildir. Mantıksal koordinatların bellekte nereye düştüğünü ve thread’lere nasıl paylaştırıldığını ifade eder.",PTX:"Bir warp kolektif çalışır; register fragment’leri çarpılır ve accumulator’lara eklenir. Son makine kodu yine SASS’tır.",WMMA:"CUDA C++ içinden warp seviyesinde Tensor Core erişimidir. Fragment’in thread’lere iç dağılımını elle varsaymamalısın."};
const quiz=[
 ["Hangisi fiziksel donanımdır?",["CUTLASS","CuTe","PTX","Tensor Core"],3,"Tensor Core, SM içindeki özel hesap birimidir."],
 ["CuTe Layout en doğru nasıl düşünülür?",["Sadece boyut","Koordinat → adres eşlemesi","PTX opcode’u","Derleyici"],1,"Layout, shape ve stride ile mantıksal koordinatı fiziksel indekse bağlar."],
 ["PTX neden son makine kodu değildir?",["CPU’da çalışır","Yalnız Python’dır","Hedef GPU için SASS’a çevrilir","Belleğe erişemez"],2,"PTX sanal ISA, SASS ise hedef mimarinin native talimatıdır."],
 ["İyi GEMM’in ana hedefi?",["Dev thread’ler","Veriyi tekrar kullanıp Tensor Core’u beslemek","Her şeyi register’a almak","Tüm sync’i silmek"],1,"Tiling ve pipeline, veri hareketini amorti edip hesap birimlerini dolu tutar."],
];
const glossary=[["GEMM","D=αAB+βC genel matris çarpımı."],["CTA","CUDA thread block."],["Warp","Birlikte yürütülen 32 thread."],["Tile","Problemin hiyerarşik küçük bloğu."],["Fragment","Warp register’larına dağılmış matris parçası."],["MMA","Multiply–accumulate, D=A×B+C."],["Epilogue","Ölçekleme, füzyon ve sonuç yazma aşaması."],["Occupancy","Aktif warp oranı; tek başına hız değildir."],["SASS","Hedef GPU’nun native talimatları."],["Arithmetic intensity","Taşınan byte başına hesap."]];

export const CUTLASS_ARCHITECTURE_IDS=["ada","hopper","blackwell","rubin"] as const;
export const CUTLASS_IMPLEMENTATION_IDS=["cpp-templates","cute-dsl","legacy-generator"] as const;
type CutlassArchitectureId=typeof CUTLASS_ARCHITECTURE_IDS[number];
type CutlassImplementationId=typeof CUTLASS_IMPLEMENTATION_IDS[number];
const implementationEvidence:Record<CutlassImplementationId,{label:string;title:string;evidence:string;sourceId:string;maturity:"current"|"preview"}>={
 "cpp-templates":{label:"C++ şablonları",title:"CUTLASS C++ şablon yolu",evidence:"Üretim kernel’inde collective, mainloop, epilogue ve schedule politikalarını CUDA C++ şablonlarıyla birleştir.",sourceId:"cutlass-cpp-templates",maturity:"current"},
 "cute-dsl":{label:"CuTe DSL",title:"CuTe DSL, CuTe C++ kavramlarıyla tutarlı",evidence:"Python-native CuTe DSL layout, tensor, hardware atom ve thread/data hiyerarşisini doğrudan ifade eder; genel kullanıma açık beta olduğundan Önizleme yoludur ve eski üretecin kısaltması değildir.",sourceId:"cutlass-cute-dsl",maturity:"preview"},
 "legacy-generator":{label:"Eski Python üreteci",title:"Eski Python üreteci ayrı bir yoldur",evidence:"Legacy Python generator, CuTe DSL değildir: CMake’in çağırdığı procedural generator şablon instantiation kodu üretir; CuTe DSL ise CuTe kavramlarıyla kernel yazan Python-native DSL’dir.",sourceId:"cutlass-legacy-generator",maturity:"current"},
};
const architectureEvidence:Record<CutlassArchitectureId,{label:string;sourceId:string;maturity:"current"|"preview";coreCompletion:boolean;evidence:string;evidenceSources:{sourceId:string;claim:string}[]}>={
 ada:{label:"Ada · SM89",sourceId:"cutlass-overview-4",maturity:"current",coreCompletion:true,evidence:"Ada için C++ template ve klasik Tensor Core yolu geçerlidir; Blackwell tcgen05.mma/TMEM yolu uygulanmaz.",evidenceSources:[]},
 hopper:{label:"Hopper · SM90",sourceId:"cutlass-overview-4",maturity:"current",coreCompletion:true,evidence:"Hopper için C++ template ve CuTe layout uygulanabilir; Blackwell’e özgü tcgen05.mma varsayılmaz.",evidenceSources:[]},
 blackwell:{label:"Blackwell · SM100",sourceId:"cutlass-blackwell-sm100",maturity:"current",coreCompletion:true,evidence:"Blackwell SM100, beşinci nesil Tensör Çekirdeği işlemlerinde tcgen05.mma, Tensör Belleği (TMEM) accumulator ve block-scaled FP4/FP8 için doğrudan uygulanabilirlik sağlar.",evidenceSources:[{sourceId:"cutlass-blackwell-sm100",claim:"tcgen05.mma, TMEM ve blok ölçekli FP4/FP8"},{sourceId:"cutlass-grouped-scheduler",claim:"Gruplu GEMM tile ataması için grouped scheduler"},{sourceId:"cutlass-blackwell-clc",claim:"Kalıcı scheduling için Blackwell Cluster Launch Control"}]},
 rubin:{label:"Rubin · SM107",sourceId:"cutlass-rubin-sm107",maturity:"preview",coreCompletion:false,evidence:"Rubin · SM107 Önizleme: ilk CuTe/C++ FP8 ve FP4 Tensor Core yolları kayıtlıdır; çalıştırmak CUDA Toolkit 13.4 GA ile gelecek R615 sürücüsünü ister. R610 Developer Preview yeterli değildir; temel tamamlanma koşulu değildir.",evidenceSources:[]},
};
export function getCutlassImplementationPlan(id:CutlassImplementationId){return implementationEvidence[id]}
export function getCutlassArchitecturePlan(id:CutlassArchitectureId){return architectureEvidence[id]}

export default function CutlassCuteEmbedded(){
 const [active,setActive]=useState(0),[tab,setTab]=useState<keyof typeof codes>("CUTLASS"),[m,setM]=useState(128),[n,setN]=useState(128),[k,setK]=useState(32),[stage,setStage]=useState(0),[qi,setQi]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0),[implementation,setImplementation]=useState<CutlassImplementationId>("cpp-templates"),[architecture,setArchitecture]=useState<CutlassArchitectureId>("blackwell");
 const metric=useMemo(()=>{const fma=m*n*k,flop=fma*2,bytes=(m*k+k*n)*2+m*n*4;return{fma,flop,ai:flop/bytes}},[m,n,k]);
 const activeImplementation=getCutlassImplementationPlan(implementation),activeArchitecture=getCutlassArchitecturePlan(architecture);
 function pick(i:number){if(answer!==null)return;setAnswer(i);if(i===quiz[qi][2])setScore(s=>s+1)}
 function next(){setQi(i=>(i+1)%quiz.length);setAnswer(null)}
 return <section className="cutlass-cute-surface" id="top" aria-labelledby="cutlass-cute-title">
  <section className="hero"><div className="heroCopy"><p className="kicker"><span>01</span>GPU KERNEL MÜHENDİSLİĞİ</p><h2 id="cutlass-cute-title">Bir matris<br/>çarpımının <em>silikona inişi.</em></h2><p className="lead">CUTLASS, CuTe, Tensor Core ve PTX aynı şey değildir. Bu atlas, aralarındaki hattı soyutlamadan donanıma kadar görünür kılar.</p><div className="actions"><a href="#map">Akışı keşfet ↓</a><a href="#basics">Önce temeller</a></div><div className="facts"><span><b>4</b> katman</span><span><b>1</b> ortak problem</span><span><b>D=A×B+C</b> çekirdek işlem</span></div></div>
   <div className="heroVisual"><small>GEMM / VERİ AKIŞI</small><div className="matrices"><div className="matrix a">{Array.from({length:24},(_,i)=><i key={i}/>) }<b>A</b></div><strong>×</strong><div className="matrix b">{Array.from({length:24},(_,i)=><i key={i}/>) }<b>B</b></div><strong>+</strong><div className="matrix c">{Array.from({length:16},(_,i)=><i key={i}/>) }<b>C</b></div></div><div className="core"><span>WARP 07 <i>MMA.SYNC</i></span><b>TENSOR CORE</b><em/></div><div className="visualFoot">FP16 GİRDİ <span>FP32 BİRİKİM</span> 32 İŞ PARÇACIĞI</div></div>
  </section>

  <section className="section" id="map"><Title n="02" tag="KAVRAM HARİTASI" title="Dört isim, dört ayrı sorumluluk." text="Satırlara tıkla. Aşağı indikçe donanıma yakınlık artar."/><div className="mapGrid"><div className="layerList" role="group" aria-label="Kavram katmanları">{layers.map((l,i)=><button key={l[0]} aria-pressed={active===i} className={active===i?`active c${i}`:""} onClick={()=>setActive(i)}><small>0{i+1}</small><b>{l[0]}<em>{l[1]}</em></b><span>{l[2]}</span><i>↘</i></button>)}</div><aside><small>AKILDA KALSIN</small><p className="cutlass-evidence-map">Problem → CUTLASS 4.x/CuTe DSL → PTX/SASS evidence → Tensor Core</p><p>Problem → CUTLASS 4.x/CuTe DSL → PTX/SASS kanıtı → Tensör Çekirdeği</p><em>CuTe, CUTLASS 3.x ve sonrasında temel yapı taşlarından biridir; rakip kütüphane değildir.</em></aside></div></section>

  <section className="section basics" id="basics"><Title n="03" tag="ÖNCE PROBLEM" title="Hız, çarpmaktan çok veriyi doğru yere getirme problemidir."/><div className="steps"><article><b>①</b><h3>Tile</h3><p>Matrisi CTA, warp ve instruction seviyesinde tekrar tekrar böl. Her seviye kendi paralellik ve bellek ölçeğine otursun.</p></article><article><b>②</b><h3>Taşı</h3><p>Global bellekten shared memory’ye, oradan register’lara veri akışını pipeline et. Veriyi yeniden kullan.</p></article><article><b>③</b><h3>Hesapla + yaz</h3><p>MMA ile accumulator’ları büyüt; epilogue’da ölçek, bias/aktivasyon gibi işleri birleştir ve sonucu yaz.</p></article></div><div className="loop"><span>AYGIT</span><b>CTA DÖŞEMESİ</b><b>WARP DÖŞEMESİ</b><b>MMA DÖŞEMESİ</b><strong>SON İŞLEM</strong></div></section>

  <section className="section cutlass-implementation-path" aria-labelledby="cutlass-implementation-title"><Title headingId="cutlass-implementation-title" n="03.5" tag="IMPLEMENTATION PATH" title="Aynı kavram, üç farklı geliştirme yolu." text="CuTe DSL, CUTLASS 4 ile gelen Python-native kernel yoludur; genel kullanıma açık beta Önizlemedir ve eski Python üreteciyle eş anlamlı değildir."/><div className="cutlass-controls" role="group" aria-label="CUTLASS uygulama yolu">{CUTLASS_IMPLEMENTATION_IDS.map(id=><button key={id} aria-pressed={implementation===id} className={implementation===id?"active":""} onClick={()=>setImplementation(id)}>{implementationEvidence[id].label}</button>)}</div><article className="cutlass-implementation-evidence" aria-live="polite" data-implementation={implementation} data-source-id={activeImplementation.sourceId} data-maturity={activeImplementation.maturity}><small>{activeImplementation.maturity==="preview"?"ÖNİZLEME · CuTe DSL public beta":"GÜNCEL · doğrudan resmî kaynak"}</small><h3>{activeImplementation.title}</h3><p>{activeImplementation.evidence}</p></article></section>

  <section className="section cutlass-architecture-gate" aria-labelledby="cutlass-architecture-title"><Title headingId="cutlass-architecture-title" n="03.6" tag="MİMARİ UYGULANABİLİRLİK" title="Kanıtı mimarinin taşıdığı yere bağla." text="Blackwell özellikleri Current’tır; Rubin/SM107 yalnızca araç zinciri uyarılı Önizleme panelinde görünür."/><div className="cutlass-controls" role="group" aria-label="CUTLASS mimari seçimi">{CUTLASS_ARCHITECTURE_IDS.map(id=><button key={id} aria-pressed={architecture===id} className={architecture===id?"active":""} onClick={()=>setArchitecture(id)}>{architectureEvidence[id].label}</button>)}</div><article className="cutlass-architecture-evidence" aria-live="polite" data-architecture={architecture} data-source-id={activeArchitecture.sourceId} data-maturity={activeArchitecture.maturity}><small>{activeArchitecture.maturity==="preview"?"ÖNİZLEME · ARAÇ ZİNCİRİ UYARISI":"GÜNCEL · MİMARİ UYGULANABİLİRLİK"}</small><h3>{activeArchitecture.label}</h3><p>{activeArchitecture.evidence}</p>{activeArchitecture.evidenceSources.map(({sourceId,claim})=><p className="cutlass-direct-evidence" data-source-id={sourceId} key={sourceId}>{claim}</p>)}{!activeArchitecture.coreCompletion&&<p><b>Önizleme yolu temel tamamlanma koşulu değildir.</b></p>}</article></section>

  <section className="lab" id="lab"><Title n="04" tag="ETKİLEŞİMLİ LAB" title="Tile’ı değiştir, maliyeti gör." text="Teorik iş miktarıdır; gerçek hız için register baskısı, occupancy, bellek düzeni ve pipeline da ölçülür." dark/><div className="labGrid"><div className="controls">{[["M",m,setM],["N",n,setN],["K",k,setK]].map(([x,v,s])=><label key={x as string}><span>{x as string} TILE <b>{v as number}</b></span><input aria-label={`${x} tile`} type="range" min="16" max={x==="K"?128:256} step="16" value={v as number} onChange={e=>(s as (v:number)=>void)(+e.target.value)}/></label>)}<div className="metrics"><span><small>FMA</small><b>{metric.fma.toLocaleString("tr-TR")}</b></span><span><small>FLOP</small><b>{metric.flop.toLocaleString("tr-TR")}</b></span><span><small>Yaklaşık yoğunluk</small><b>{metric.ai.toFixed(1)} F/B</b></span></div></div><div className="tile"><small>CTA DÖŞEMESİ · {m}×{n}×{k}</small><div>{Array.from({length:48},(_,i)=><i className={i%3===0?"hot":""} key={i}/>)}<b>WARP DÖŞEMESİ<br/><em>{Math.min(64,m)}×{Math.min(64,n)}</em></b></div></div></div><div className="pipeline" role="group" aria-label="Veri hattı aşaması">{["GMEM → SMEM","SMEM → REG","MMA","EPILOGUE"].map((x,i)=><button aria-pressed={stage===i} className={stage===i?"active":""} onClick={()=>setStage(i)} key={x}><small>0{i+1}</small><b>{x}</b><span>{["eşzamansız / birleşik kopya","döşemeli kopya / ldmatrix","Tensor Core birikimi","ölçekle / birleştir / yaz"][i]}</span></button>)}</div></section>

  <section className="section" id="code"><Title n="05" tag="AYNI İŞ, FARKLI SEVİYELER" title="Kodun soyutlamadan talimata inişini izle."/><div className="tabs" role="group" aria-label="Kod soyutlama seviyesi">{Object.keys(codes).map(x=><button aria-pressed={tab===x} className={tab===x?"active":""} key={x} onClick={()=>setTab(x as keyof typeof codes)}>{x}</button>)}</div><div className="code"><pre tabIndex={0} aria-label="Kod örneği">{codes[tab]}</pre><aside><small>NE ANLATIYOR?</small><p>{notes[tab]}</p></aside></div><div className="warn"><b>⚠</b><p><strong>PTX görmek, GPU’nun gerçekten onu yürüttüğü anlamına gelmez.</strong> Sürücü PTX’i hedef mimarinin SASS talimatlarına çevirir. Son doğrulama disassembly ve profiler ile yapılır.</p></div></section>

  <section className="section deep"><Title n="06" tag="DERİN DALIŞ" title="Her katmanda neyi kontrol edersin?"/><div className="cards"><Deep name="CUTLASS" sub="CUDA C++ ŞABLONLARI" title="Parçaları üretim kernel’ine toplar." items={["Collective mainloop + epilogue","Tile, schedule ve datatype politikaları","GEMM, convolution ve grouped GEMM","Profiler ile kernel keşfi"]} best="Özel ama kanıtlanmış yüksek performanslı operatör."/><Deep name="CuTe" sub="YERLEŞİM CEBİRİ" title="İndeks muhasebesini dile çevirir." items={["Shape, stride ve composition","Tensor view ve coordinate engine","TiledCopy / TiledMMA","Derleme zamanı statik şekiller"]} best="Thread–data eşlemesini açıkça tasarlamak."/><Deep name="PTX" sub="SANAL ISA" title="Derleyici ile makine kodu arasındaki sözleşmedir." items={["Register, predicate ve address space","mma / ldmatrix / cp.async","Kontrollü inline PTX","ISA ve compute capability hedefleri"]} best="Derleyici çıktısını anlamak veya özel talimata erişmek."/><Deep name="TENSOR CORE" sub="HARDWARE" title="Küçük matris MAC işlemlerini yürütür." items={["Warp/warpgroup kolektif hesap","Karışık hassasiyet","Desteklenen sparse MMA","Beslenmezse tepe değer anlamsız"]} best="GEMM, attention ve convolution."/></div></section>

  <section className="section decision"><Title n="07" tag="KARAR REHBERİ" title="Hangi seviyeden başlamalısın?"/><div className="table"><div><b>İhtiyaç</b><b>Başlangıç</b><b>Neden</b></div><div><span>Hazır, hızlı GEMM</span><strong>cuBLAS / framework</strong><span>En düşük geliştirme maliyeti; güçlü baseline.</span></div><div><span>Özel epilogue veya shape</span><strong>CUTLASS</strong><span>Hazır parçalarla kontrollü özelleştirme.</span></div><div><span>Yeni layout / dataflow</span><strong>CuTe</strong><span>Thread–data eşlemesini kurulabilir ifade eder.</span></div><div><span>Talimat düzeyi kontrol</span><strong>PTX + CuTe atomları</strong><span>Özel araştırma; mimari bağımlılığı yüksek.</span></div></div><p className="rule"><b>Altın kural:</b> Önce doğruluk, sonra profiler, sonra daha düşük soyutlama. PTX’e gösteriş için değil, ölçümün gösterdiği darboğaz için in.</p></section>

  <section className="quiz" id="quiz"><div><p className="kicker"><span>08</span>KENDİNİ SINA</p><h2>Kavramlar yerine oturdu mu?</h2><p>Ezberi değil, katmanlar arasındaki ayrımı ölçen 4 soru.</p><b className="score">SKOR <span>{score}/{quiz.length}</span></b></div><article><small>SORU {qi+1} / {quiz.length}</small><h3>{quiz[qi][0] as string}</h3><div className="answers" role="group" aria-label="Yanıt seçenekleri">{(quiz[qi][1] as string[]).map((x,i)=><button key={x} aria-pressed={answer===i} onClick={()=>pick(i)} className={answer===null?"":i===quiz[qi][2]?"ok":answer===i?"no":"off"}><i>{String.fromCharCode(65+i)}</i>{x}</button>)}</div><div className="quiz-feedback" aria-live="polite" hidden={answer===null}>{answer===null ? null : <><p>{answer===quiz[qi][2]?"Doğru. ":"Henüz değil. "}{quiz[qi][3] as string}</p><button onClick={next}>Sonraki →</button></>}</div></article></section>

  <section className="section"><Title n="09" tag="HIZLI SÖZLÜK" title="Profiler açmadan önce aynı dili konuş."/><div className="glossary">{glossary.map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>
  <section className="sources" id="sources"><div><p className="kicker"><span>10</span>RESMÎ KAYNAKLAR</p><h2>Atlas biter, dokümantasyon başlar.</h2></div><div>{[["CUTLASS Documentation","https://docs.nvidia.com/cutlass/latest/","Genel bakış, API ve örnekler"],["CuTe Documentation","https://docs.nvidia.com/cutlass/latest/media/docs/cpp/cute/index.html","Layout, tensor ve GEMM tutorial"],["PTX ISA","https://docs.nvidia.com/cuda/parallel-thread-execution/","Talimatlar ve bellek modeli"],["CUDA C++ Guide","https://docs.nvidia.com/cuda/cuda-c-programming-guide/","Programlama modeli ve WMMA"]].map((x,i)=><a key={x[0]} href={x[1]} target="_blank" rel="noreferrer"><small>0{i+1}</small><b>{x[0]}</b><span>{x[2]}</span><i>↗</i></a>)}</div></section>
 </section>
}
function Title({n,tag,title,text,dark,headingId}:{n:string,tag:string,title:string,text?:string,dark?:boolean;headingId?:string}){return <div className={`title ${dark?"dark":""}`}><p className="kicker"><span>{n}</span>{tag}</p><h2 id={headingId}>{title}</h2>{text&&<p>{text}</p>}</div>}
function Deep({name,sub,title,items,best}:{name:string,sub:string,title:string,items:string[],best:string}){return <article><div><b>{name}</b><small>{sub}</small></div><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><p><b>En iyi kullanım:</b> {best}</p></article>}
