"use client";
/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- Labelled overflow regions must remain keyboard-scrollable. */
import {useMemo,useState} from "react";

const layers=[
 ["CUTLASS","Library","Configurable CUDA C++ templates for production-quality GEMM and associated operations."],
 ["CuTe","Layout algebra","Expresses coordinate-to-address mapping, tensor partitioning, copies, and MMA layouts through shapes and strides."],
 ["PTX","Virtual ISA","A portable intermediate instruction language between the compiler and target-specific machine code."],
 ["Tensor Core","Hardware","Specialized compute units that execute D=A×B+C efficiently on small matrix fragments."],
];
const codes={
 CUTLASS:`using Gemm = cutlass::gemm::device::Gemm<\n  cutlass::half_t, RowMajor,\n  cutlass::half_t, ColumnMajor,\n  float, RowMajor\n>;\n\nGemm op;\nop({problem, A, B, C, D, alpha, beta});`,
 CuTe:`auto layout = make_layout(\n  make_shape(Int<128>{}, Int<64>{}),\n  make_stride(Int<1>{}, Int<128>{})\n);\n\nauto tensor = make_tensor(ptr, layout);\nauto tile = local_tile(tensor, tile_shape, coord);`,
 PTX:`mma.sync.aligned.m16n8k16\n  .row.col.f32.f16.f16.f32\n  {d0, d1, d2, d3},\n  {a0, a1, a2, a3},\n  {b0, b1},\n  {c0, c1, c2, c3};`,
 WMMA:`wmma::load_matrix_sync(a, A, lda);\nwmma::load_matrix_sync(b, B, ldb);\nwmma::mma_sync(c, a, b, c);\nwmma::store_matrix_sync(D, c, ldd,\n  wmma::mem_row_major);`,
};
const notes={CUTLASS:"You describe the problem and policies; the library assembles the mainloop, data movement, MMA, and epilogue components.",CuTe:"A layout is more than a size. It expresses where logical coordinates land in memory and how data is partitioned across threads.",PTX:"A warp operates collectively: register fragments are multiplied and added to accumulators. The final machine code is still SASS.",WMMA:"WMMA provides warp-level Tensor Core access from CUDA C++. Do not assume how a fragment is distributed internally across threads."};
const quiz=[
 ["Which one is physical hardware?",["CUTLASS","CuTe","PTX","Tensor Core"],3,"Tensor Cores are specialized compute units inside an SM."],
 ["What is the best mental model for a CuTe layout?",["Size only","Coordinate → address mapping","A PTX opcode","A compiler"],1,"A layout connects logical coordinates to physical indices through shapes and strides."],
 ["Why isn't PTX the final machine code?",["Runs on CPU","It's just Python","Converted to SASS for target GPU","Cannot access memory"],2,"PTX is the virtual ISA and SASS is the native instruction of the target architecture."],
 ["What is the main goal of a fast GEMM?",["Use huge threads","Reuse data and feed Tensor Cores","Put everything in registers","Remove every synchronization"],1,"Tiling and pipelining amortize data movement and keep compute units busy."],
];
const glossary=[["GEMM","General matrix multiplication: D=αAB+βC."],["CTA","A CUDA thread block."],["Warp","A group of 32 threads executed together."],["Tile","A hierarchical sub-block of the problem."],["Fragment","A matrix fragment distributed across warp registers."],["MMA","Matrix multiply–accumulate: D=A×B+C."],["Epilogue","The scaling, fusion, and result-write stage."],["Occupancy","The active-warp ratio; it is not a speed metric by itself."],["SASS","Native instructions for the target GPU."],["Arithmetic intensity","Computation performed per byte moved."]];

export const CUTLASS_ARCHITECTURE_IDS=["ada","hopper","blackwell","rubin"] as const;
export const CUTLASS_IMPLEMENTATION_IDS=["cpp-templates","cute-dsl","legacy-generator"] as const;
type CutlassArchitectureId=typeof CUTLASS_ARCHITECTURE_IDS[number];
type CutlassImplementationId=typeof CUTLASS_IMPLEMENTATION_IDS[number];
const implementationEvidence:Record<CutlassImplementationId,{label:string;title:string;evidence:string;sourceId:string;maturity:"current"|"preview"}>={
 "cpp-templates":{label:"C++ templates",title:"CUTLASS C++ template path",evidence:"Compose collective, mainloop, epilogue, and scheduling policies through CUDA C++ templates for a production kernel.",sourceId:"cutlass-cpp-templates",maturity:"current"},
 "cute-dsl":{label:"CuTe DSL",title:"CuTe DSL is consistent with CuTe C++ concepts",evidence:"The Python-native CuTe DSL expresses layouts, tensors, hardware atoms, and the thread/data hierarchy directly; it remains a public-beta Preview path and is not an alias for the legacy generator.",sourceId:"cutlass-cute-dsl",maturity:"preview"},
 "legacy-generator":{label:"Legacy Python generator",title:"The legacy Python generator is a separate path",evidence:"The legacy Python generator is not CuTe DSL: CMake invokes its procedural generator to produce template instantiations, while CuTe DSL is a Python-native DSL for writing kernels through CuTe concepts.",sourceId:"cutlass-legacy-generator",maturity:"current"},
};
const architectureEvidence:Record<CutlassArchitectureId,{label:string;sourceId:string;maturity:"current"|"preview";coreCompletion:boolean;evidence:string;evidenceSources:{sourceId:string;claim:string}[]}>={
 ada:{label:"Ada · SM89",sourceId:"cutlass-overview-4",maturity:"current",coreCompletion:true,evidence:"Ada uses the C++ template and established Tensor Core path; Blackwell tcgen05.mma/TMEM is not applicable.",evidenceSources:[]},
 hopper:{label:"Hopper · SM90",sourceId:"cutlass-overview-4",maturity:"current",coreCompletion:true,evidence:"Hopper can use C++ templates and CuTe layouts; it does not imply Blackwell-only tcgen05.mma.",evidenceSources:[]},
 blackwell:{label:"Blackwell · SM100",sourceId:"cutlass-blackwell-sm100",maturity:"current",coreCompletion:true,evidence:"Blackwell SM100 directly applies fifth-generation Tensor Core operations: tcgen05.mma, Tensor Memory (TMEM) accumulators, and block-scaled FP4/FP8.",evidenceSources:[{sourceId:"cutlass-blackwell-sm100",claim:"tcgen05.mma, TMEM, and block-scaled FP4/FP8"},{sourceId:"cutlass-grouped-scheduler",claim:"Grouped GEMM tile assignment through the grouped scheduler"},{sourceId:"cutlass-blackwell-clc",claim:"Persistent scheduling through Blackwell Cluster Launch Control"}]},
 rubin:{label:"Rubin · SM107",sourceId:"cutlass-rubin-sm107",maturity:"preview",coreCompletion:false,evidence:"Rubin · SM107 Preview: initial CuTe/C++ FP8 and FP4 Tensor Core paths are recorded; execution requires the R615 driver that arrives with CUDA Toolkit 13.4 GA. R610 Developer Preview is insufficient, and this is not a core completion requirement.",evidenceSources:[]},
};
export function getCutlassImplementationPlan(id:CutlassImplementationId){return implementationEvidence[id]}
export function getCutlassArchitecturePlan(id:CutlassArchitectureId){return architectureEvidence[id]}

export default function CutlassCuteEmbedded(){
 const [active,setActive]=useState(0),[tab,setTab]=useState<keyof typeof codes>("CUTLASS"),[m,setM]=useState(128),[n,setN]=useState(128),[k,setK]=useState(32),[stage,setStage]=useState(0),[qi,setQi]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0),[implementation,setImplementation]=useState<CutlassImplementationId>("cpp-templates"),[architecture,setArchitecture]=useState<CutlassArchitectureId>("blackwell");
 const metric=useMemo(()=>{const fma=m*n*k,flop=fma*2,bytes=(m*k+k*n)*2+m*n*4;return{fma,flop,ai:flop/bytes}},[m,n,k]);
 const activeImplementation=getCutlassImplementationPlan(implementation),activeArchitecture=getCutlassArchitecturePlan(architecture);
 function pick(i:number){if(answer!==null)return;setAnswer(i);if(i===quiz[qi][2])setScore(s=>s+1)}
 function next(){setQi(i=>(i+1)%quiz.length);setAnswer(null)}
 return <section className="cutlass-cute-surface" id="top" aria-labelledby="cutlass-cute-title">
  <section className="hero"><div className="heroCopy"><p className="kicker"><span>01</span>GPU KERNEL ENGINEERING</p><h2 id="cutlass-cute-title">A matrix<br/><em>descends into silicon.</em></h2><p className="lead">CUTLASS, CuTe, Tensor Cores, and PTX are not the same thing. This atlas traces their path from abstraction to hardware.</p><div className="actions"><a href="#map">Explore the flow ↓</a><a href="#basics">Start with the basics</a></div><div className="facts"><span><b>4</b> layers</span><span><b>1</b> common problem</span><span><b>D=A×B+C</b> core operation</span></div></div>
   <div className="heroVisual"><small>GEMM/DATAFLOW</small><div className="matrices"><div className="matrix a">{Array.from({length:24},(_,i)=><i key={i}/>) }<b>A.</b></div><strong>×</strong><div className="matrix b">{Array.from({length:24},(_,i)=><i key={i}/>) }<b>B.</b></div><strong>+</strong><div className="matrix c">{Array.from({length:16},(_,i)=><i key={i}/>) }<b>C.</b></div></div><div className="core"><span>WARP 07 <i>MMA.SYNC</i></span><b>TENSOR CORE</b><em/></div><div className="visualFoot">FP16 INPUT <span>FP32 ACCUMULATE</span> 32 THREADS</div></div>
  </section>

  <section className="section" id="map"><Title n="02" tag="CONCEPT MAP" title="Four names, four distinct responsibilities." text="Select a row. Each step downward moves closer to the hardware."/><div className="mapGrid"><div className="layerList" role="group" aria-label="Concept layers">{layers.map((l,i)=><button key={l[0]} aria-pressed={active===i} className={active===i?`active c${i}`:""} onClick={()=>setActive(i)}><small>0{i+1}</small><b>{l[0]}<em>{l[1]}</em></b><span>{l[2]}</span><i>↘</i></button>)}</div><aside><small>KEEP IN MIND</small><p className="cutlass-evidence-map">Problem → CUTLASS 4.x/CuTe DSL → PTX/SASS evidence → Tensor Core</p><em>CuTe is a core building block in CUTLASS 3.x and later, not a competing library.</em></aside></div></section>

  <section className="section basics" id="basics"><Title n="03" tag="PROBLEM FIRST" title="Speed depends less on multiplication than on moving data to the right place."/><div className="steps"><article><b>①</b><h3>Tile</h3><p>Partition the matrix at CTA, warp, and instruction levels so each level matches its parallelism and memory scale.</p></article><article><b>②</b><h3>Move</h3><p>Pipeline data from global memory to shared memory and then to registers. Reuse it whenever possible.</p></article><article><b>③</b><h3>Compute + write</h3><p>Accumulate with MMA; in the epilogue, fuse scaling, bias, activation, and the final store.</p></article></div><div className="loop"><span>DEVICE</span><b>CTA TILE</b><b>WARP TILE</b><b>MMA TILE</b><strong>EPILOGUE</strong></div></section>

  <section className="section cutlass-implementation-path" aria-labelledby="cutlass-implementation-title"><Title headingId="cutlass-implementation-title" n="03.5" tag="IMPLEMENTATION PATH" title="One concept, three development paths." text="CuTe DSL is the Python-native kernel path introduced with CUTLASS 4; it remains a public-beta Preview and is not another name for the legacy Python generator."/><div className="cutlass-controls" role="group" aria-label="CUTLASS implementation path">{CUTLASS_IMPLEMENTATION_IDS.map(id=><button key={id} aria-pressed={implementation===id} className={implementation===id?"active":""} onClick={()=>setImplementation(id)}>{implementationEvidence[id].label}</button>)}</div><article className="cutlass-implementation-evidence" aria-live="polite" data-implementation={implementation} data-source-id={activeImplementation.sourceId} data-maturity={activeImplementation.maturity}><small>{activeImplementation.maturity==="preview"?"PREVIEW · CuTe DSL public beta":"CURRENT · direct official source"}</small><h3>{activeImplementation.title}</h3><p>{activeImplementation.evidence}</p></article></section>

  <section className="section cutlass-architecture-gate" aria-labelledby="cutlass-architecture-title"><Title headingId="cutlass-architecture-title" n="03.6" tag="ARCHITECTURE APPLICABILITY" title="Attach evidence to the architecture that carries it." text="Blackwell features are Current; Rubin/SM107 appears only in a toolchain-caveated Preview panel."/><div className="cutlass-controls" role="group" aria-label="CUTLASS architecture selection">{CUTLASS_ARCHITECTURE_IDS.map(id=><button key={id} aria-pressed={architecture===id} className={architecture===id?"active":""} onClick={()=>setArchitecture(id)}>{architectureEvidence[id].label}</button>)}</div><article className="cutlass-architecture-evidence" aria-live="polite" data-architecture={architecture} data-source-id={activeArchitecture.sourceId} data-maturity={activeArchitecture.maturity}><small>{activeArchitecture.maturity==="preview"?"PREVIEW · TOOLCHAIN CAVEAT":"CURRENT · ARCHITECTURE APPLICABILITY"}</small><h3>{activeArchitecture.label}</h3><p>{activeArchitecture.evidence}</p>{activeArchitecture.evidenceSources.map(({sourceId,claim})=><p className="cutlass-direct-evidence" data-source-id={sourceId} key={sourceId}>{claim}</p>)}{!activeArchitecture.coreCompletion&&<p><b>This Preview path is not a core completion requirement.</b></p>}</article></section>

  <section className="lab" id="lab"><Title n="04" tag="INTERACTIVE LAB" title="Change the tile and inspect the cost." text="These are theoretical work estimates; real performance also depends on register pressure, occupancy, memory layout, and pipelining." dark/><div className="labGrid"><div className="controls">{[["M",m,setM],["N",n,setN],["K",k,setK]].map(([x,v,s])=><label key={x as string}><span>{x as string} TILE <b>{v as number}</b></span><input aria-label={`${x} tile`} type="range" min="16" max={x==="K"?128:256} step="16" value={v as number} onChange={e=>(s as (v:number)=>void)(+e.target.value)}/></label>)}<div className="metrics"><span><small>FMA</small><b>{metric.fma.toLocaleString("en-US")}</b></span><span><small>FLOP</small><b>{metric.flop.toLocaleString("en-US")}</b></span><span><small>Approx. intensity</small><b>{metric.ai.toFixed(1)} F/B</b></span></div></div><div className="tile"><small>CTA TILE · {m}×{n}×{k}</small><div>{Array.from({length:48},(_,i)=><i className={i%3===0?"hot":""} key={i}/>)}<b>WARP TILE<br/><em>{Math.min(64,m)}×{Math.min(64,n)}</em></b></div></div></div><div className="pipeline" role="group" aria-label="Pipeline stage">{["GMEM → SMEM","SMEM → REG","MMA","EPILOGUE"].map((x,i)=><button aria-pressed={stage===i} className={stage===i?"active":""} onClick={()=>setStage(i)} key={x}><small>0{i+1}</small><b>{x}</b><span>{["async / coalesced copy","tiled copy / ldmatrix","tensor core accumulate","scale / fuse / store"][i]}</span></button>)}</div></section>

  <section className="section" id="code"><Title n="05" tag="SAME JOB, DIFFERENT LEVELS" title="Watch the code descend from abstraction to instruction."/><div className="tabs" role="group" aria-label="Code abstraction level">{Object.keys(codes).map(x=><button aria-pressed={tab===x} className={tab===x?"active":""} key={x} onClick={()=>setTab(x as keyof typeof codes)}>{x}</button>)}</div><div className="code"><pre tabIndex={0} aria-label="Code example">{codes[tab]}</pre><aside><small>WHAT DOES IT MEAN?</small><p>{notes[tab]}</p></aside></div><div className="warn"><b>⚠</b><p><strong>Seeing PTX doesn't mean the GPU is actually running it.</strong> The driver translates PTX into SASS instructions of the target architecture. Final verification is done with disassembly and profiler.</p></div></section>

  <section className="section deep"><Title n="06" tag="DEEP DIVE" title="What do you control at each layer?"/><div className="cards"><Deep name="CUTLASS" sub="CUDA C++ TEMPLATES" title="Assembles components into a production kernel." items={["Collective mainloop + epilogue","Tile, schedule, and data-type policies","GEMM, convolution, and grouped GEMM","Kernel discovery with the profiler"]} best="A specialized, proven high-performance operator."/><Deep name="CuTe" sub="LAYOUT ALGEBRA" title="Turns index bookkeeping into a language." items={["Shape, stride, and composition","Tensor views and coordinate engines","TiledCopy / TiledMMA","Compile-time static shapes"]} best="Designing thread-to-data mappings explicitly."/><Deep name="PTX" sub="VIRTUAL ISA" title="Defines the contract between compiler and machine code." items={["Registers, predicates, and address spaces","mma / ldmatrix / cp.async","Controlled inline PTX","ISA and compute-capability targets"]} best="Understanding compiler output or accessing a specialized instruction."/><Deep name="TENSOR CORE" sub="HARDWARE" title="Executes small-matrix multiply–accumulate operations." items={["Warp/warpgroup collective compute","Mixed precision","Supported sparse MMA","Peak throughput is meaningless when starved"]} best="GEMM, attention, and convolution."/></div></section>

  <section className="section decision"><Title n="07" tag="DECISION GUIDE" title="Which level should you start from?"/><div className="table"><div><b>Need</b><b>Starting point</b><b>Why</b></div><div><span>Ready-to-use fast GEMM</span><strong>cuBLAS / framework</strong><span>Lowest development cost and a strong baseline.</span></div><div><span>Custom epilogue or shape</span><strong>CUTLASS</strong><span>Controlled customization with proven components.</span></div><div><span>New layout / dataflow</span><strong>CuTe</strong><span>Expresses a configurable thread-to-data mapping.</span></div><div><span>Instruction-level control</span><strong>PTX + CuTe atoms</strong><span>Specialized research with high architecture dependence.</span></div></div><p className="rule"><b>Golden rule:</b> Prove correctness, profile, and only then lower the abstraction. Use PTX for a measured bottleneck, not for show.</p></section>

  <section className="quiz" id="quiz"><div><p className="kicker"><span>08</span>TEST YOURSELF</p><h2>Do the layers make sense?</h2><p>Four questions test whether you can distinguish the layers instead of merely memorizing terms.</p><b className="score">SCORE <span>{score}/{quiz.length}</span></b></div><article><small>QUESTION {qi+1} / {quiz.length}</small><h3>{quiz[qi][0] as string}</h3><div className="answers" role="group" aria-label="Answer choices">{(quiz[qi][1] as string[]).map((x,i)=><button key={x} aria-pressed={answer===i} onClick={()=>pick(i)} className={answer===null?"":i===quiz[qi][2]?"ok":answer===i?"no":"off"}><i>{String.fromCharCode(65+i)}</i>{x}</button>)}</div><div className="quiz-feedback" aria-live="polite" hidden={answer===null}>{answer===null ? null : <><p>{answer===quiz[qi][2]?"Correct. ":"Not yet. "}{quiz[qi][3] as string}</p><button onClick={next}>Next →</button></>}</div></article></section>

  <section className="section"><Title n="09" tag="QUICK DICTIONARY" title="Speak the same language before opening Profiler."/><div className="glossary">{glossary.map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>
  <section className="sources" id="sources"><div><p className="kicker"><span>10</span>OFFICIAL SOURCES</p><h2>Atlas ends, documentation begins.</h2></div><div>{[["CUTLASS Documentation","https://docs.nvidia.com/cutlass/latest/","Overview, API and examples"],["CuTe Documentation","https://docs.nvidia.com/cutlass/latest/media/docs/cpp/cute/index.html","Layout, tensor and GEMM tutorial"],["PTX ISA","https://docs.nvidia.com/cuda/parallel-thread-execution/","Instructions and memory model"],["CUDA C++ Guide","https://docs.nvidia.com/cuda/cuda-c-programming-guide/","Programming model and WMMA"]].map((x,i)=><a key={x[0]} href={x[1]} target="_blank" rel="noreferrer"><small>0{i+1}</small><b>{x[0]}</b><span>{x[2]}</span><i>↗</i></a>)}</div></section>
 </section>
}
function Title({n,tag,title,text,dark,headingId}:{n:string,tag:string,title:string,text?:string,dark?:boolean;headingId?:string}){return <div className={`title ${dark?"dark":""}`}><p className="kicker"><span>{n}</span>{tag}</p><h2 id={headingId}>{title}</h2>{text&&<p>{text}</p>}</div>}
function Deep({name,sub,title,items,best}:{name:string,sub:string,title:string,items:string[],best:string}){return <article><div><b>{name}</b><small>{sub}</small></div><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><p><b>Best use:</b> {best}</p></article>}
