export const uiByLocale = {
  tr: {
    home: "GPU Kernel Atlas ana sayfa", mainNav: "Ana navigasyon", weeks: "12 hafta",
    progress: "İlerleme yüzde", menu: "Atlas menüsünü aç", search: "Atlas içinde ara", command: "Komuta merkezi",
    unified: "12 BİRLEŞİK ATLAS", learningAtlases: "Öğrenme atlasları", localProgress: "YEREL İLERLEME", stored: "Bu cihazda saklanır.",
    eyebrow: "BİRLEŞİK ÖĞRENME SİSTEMİ · 2026", headlineA: "Kernel’i yaz.", headlineB: "Sistemi anla.", headlineC: "Kanıtla.",
    hero: "On iki etkileşimli atlas; görsel GPU temellerini, tile düzeyi programlamayı, Blackwell farkındalıklı optimizasyonu ve dağıtık çıkarımı, desteklenen mimari ve backend sınırlarını görünür kılan 12 haftalık kanıt rotasında birleştirir.",
    start: "Öğrenmeye başla", viewWeeks: "12 haftayı gör", atlasStat: "birleşik atlas", weekStat: "yoğun hafta", operatorStat: "LLM operatörü", gateStat: "kanıt kapısı",
    graph: "ÖĞRENME GRAFİĞİ", online: "ÇEVRİM İÇİ", correctness: "DOĞRULUK", measurement: "ÖLÇÜM", integration: "ENTEGRASYON",
    principle1: "Referans, şekil/dtype matrisi ve sanitizer temizliği olmadan kernel tamamlanmış sayılmaz.", principle2: "Warm-up, quantile, profiler ve kontrollü baseline olmadan hız iddiası kurulmaz.", principle3: "Gerçek hedef; PyTorch, compile ve serving iş yükü içinde çalışan portföy kalitesinde operatördür.",
    map: "ATLAS HARİTASI", mapA: "Tek uygulama.", mapB: "On iki uzmanlık alanı.", mapNote: "Görsel temellerden capstone’a ilerleyen rota. Her atlas kendi etkileşimli laboratuvarını, Concept Studio’sunu, karar modelini ve kabul çıktısını içerir.", done: "TAMAMLANDI", completionStatus: "Tamamlandı",
    route: "12 HAFTALIK YOĞUN ROTA", routeA: "Okuma listesi değil.", routeB: "Üretim sistemi.", routeNote: "Haftada 14–16 saat. Her hafta çalışan kod, doğruluk kanıtı veya ölçüm raporu üretir.",
    graduation: "MEZUNİYET KAPISI", dual: "CUDA/Triton\nçift uygulama", gain: "iki fused kernel\nmedyan kazanç", studies: "Nsight\nincelemesi", report: "vLLM TTFT/ITL/\nthroughput raporu", interview: "mülakat\nsavunması",
    interactive: "ETKİLEŞİMLİ ATLAS", evidence: "ÇIKIŞ KANITI", learned: "Öğrendin mi?", record: "Kanıtını kaydet.", complete: "Atlası tamamla", completed: "✓ Tamamlandı", next: "Sonraki atlas →",
    continue: "Devam et", clearSearch: "Aramayı temizle", noResults: "Sonuç bulunamadı.", closeMenu: "Atlas menüsünü kapat", maturity: "Olgunluk", architectures: "Mimariler", previewCaveat: "Önizleme içeriği, desteklenen araç zincirlerine bağlıdır.",
    maturityLabels: { core: "Temel", current: "Güncel", preview: "Önizleme" },
    maturityDefinitions: {
      core: "Temel: donanım kuşağından bağımsız, tamamlanması gereken beceri ve kanıt.",
      current: "Güncel: güncel birinci taraf kanıtla desteklenir; mimari ve backend uygulanabilirliği ayrıca doğrulanır.",
      preview: "Önizleme: araç zinciri ya da donanım olgunlaşmasına bağlı keşif yoludur; mezuniyet koşulu değildir.",
    },
    evidencePolicy: "Birinci taraf kaynaklar yayın öncesinde tazelenir; belge güncelliği, özellik olgunluğu ve mimari/backend uygulanabilirliği ayrı değerlendirilir.",
    simulationCaveat: "Etkileşimli laboratuvarlar eğitim amaçlı simülasyonlardır; ölçülmüş donanım sonucu iddia etmez.",
    architectureMatrix: "MİMARİ UYGULANABİLİRLİĞİ", architectureTitleA: "Temelden önizlemeye.", architectureTitleB: "Desteği görünür kıl.",
    architectureNote: "Her mimari etiketi, kavramların uygulanabilirliğini ve olgunluğunu gösterir; en yeni donanıma sahip olduğunuzu varsaymaz.",
    architectureDescriptions: {
      ada: "Warp, bellek, doluluk ve klasik Tensor Core çalışmaları için yerleşik çekirdek taban.",
      hopper: "TMA, warp-group MMA, dağıtık paylaşılan bellek ve kalıcı zamanlama için güncel temel.",
      blackwell: "Tensor Memory, beşinci nesil Tensor Core, blok ölçekli FP4/FP8 ve küme duyarlı zamanlama.",
      rubin: "Yalnızca güncel birinci taraf araç zincirlerinin belgelediği yeteneklerle sınırlı önizleme materyali.",
    },
    moduleUnavailable: "Bu laboratuvar şu anda kullanılamıyor. İçerik uydurulmadı; genel bakıştan başka bir atlas seçebilirsiniz.",
    showOverview: "Genel bakışa dön",
  },
  en: {
    home: "GPU Kernel Atlas home", mainNav: "Main navigation", weeks: "12 weeks",
    progress: "Progress percent", menu: "Open atlas menu", search: "Search the atlas", command: "Command center",
    unified: "12 UNIFIED ATLASES", learningAtlases: "Learning atlases", localProgress: "LOCAL PROGRESS", stored: "Stored on this device.",
    eyebrow: "UNIFIED LEARNING SYSTEM · 2026", headlineA: "Write the kernel.", headlineB: "Understand the system.", headlineC: "Prove it.",
    hero: "Twelve interactive atlases connect visual GPU foundations, tile-level programming, Blackwell-aware optimization, and distributed inference in a 12-week evidence route that makes supported architecture and backend boundaries visible.",
    start: "Start learning", viewWeeks: "View the 12 weeks", atlasStat: "unified atlases", weekStat: "intensive weeks", operatorStat: "LLM operators", gateStat: "evidence gates",
    graph: "LEARNING GRAPH", online: "ONLINE", correctness: "CORRECTNESS", measurement: "MEASUREMENT", integration: "INTEGRATION",
    principle1: "A kernel is not complete without a reference, a shape/dtype matrix, and clean sanitizer results.", principle2: "No performance claim without warm-up, quantiles, profiler evidence, and a controlled baseline.", principle3: "The real goal is a portfolio-grade operator that works in PyTorch, compile, and serving workloads.",
    map: "ATLAS MAP", mapA: "One application.", mapB: "Twelve domains.", mapNote: "A route from visual foundations to capstone. Every atlas includes an interactive lab, a Concept Studio, a decision model, and an acceptance artifact.", done: "COMPLETED", completionStatus: "Completed",
    route: "12-WEEK INTENSIVE ROUTE", routeA: "Not a reading list.", routeB: "A production system.", routeNote: "14–16 hours per week. Every week produces working code, correctness evidence, or a measurement report.",
    graduation: "GRADUATION GATE", dual: "CUDA/Triton\ndual implementation", gain: "median gain across\ntwo fused kernels", studies: "Nsight\nstudies", report: "vLLM TTFT/ITL/\nthroughput report", interview: "interview\ndefense",
    interactive: "INTERACTIVE ATLAS", evidence: "EXIT EVIDENCE", learned: "Did you learn it?", record: "Record the evidence.", complete: "Complete atlas", completed: "✓ Completed", next: "Next atlas →",
    continue: "Continue", clearSearch: "Clear search", noResults: "No results found.", closeMenu: "Close atlas menu", maturity: "Maturity", architectures: "Architectures", previewCaveat: "Preview content depends on supported toolchains.",
    maturityLabels: { core: "Core", current: "Current", preview: "Preview" },
    maturityDefinitions: {
      core: "Core: hardware-generation-independent skills and evidence required for completion.",
      current: "Current: supported by fresh first-party evidence; architecture and backend applicability are verified separately.",
      preview: "Preview: an exploration path dependent on toolchain or hardware maturity; it is not a graduation requirement.",
    },
    evidencePolicy: "First-party sources are refreshed before publication; document freshness, feature maturity, and architecture/backend applicability are evaluated separately.",
    simulationCaveat: "Interactive laboratories are educational simulations; they do not claim measured hardware results.",
    architectureMatrix: "ARCHITECTURE APPLICABILITY", architectureTitleA: "From baseline to preview.", architectureTitleB: "Make support visible.",
    architectureNote: "Each architecture label describes concept applicability and maturity; it does not assume that you own the newest hardware.",
    architectureDescriptions: {
      ada: "Established core baseline for warp, memory, occupancy, and classic Tensor Core work.",
      hopper: "Current foundation for TMA, warp-group MMA, distributed shared memory, and persistent scheduling.",
      blackwell: "Tensor Memory, fifth-generation Tensor Cores, block-scaled FP4/FP8, and cluster-aware scheduling.",
      rubin: "Preview material limited to capabilities documented by current first-party toolchains.",
    },
    moduleUnavailable: "This laboratory is currently unavailable. No content was fabricated; choose another atlas from the overview.",
    showOverview: "Return to overview",
  },
} as const;
