import type { Maturity, ModuleId } from "./types";

export type CurriculumSource = Readonly<{
  id: string;
  moduleId: ModuleId;
  title: string;
  url: `https://${string}`;
  verifiedAt: "2026-09-04";
  maturity: Maturity;
}>;

export const curriculumSources = [
  {
    id: "cuda-guide-visual-foundations",
    moduleId: "visual",
    title: "CUDA Programming Guide",
    url: "https://docs.nvidia.com/cuda/cuda-programming-guide/",
    verifiedAt: "2026-09-04",
    maturity: "core",
  },
  {
    id: "cuda-install",
    moduleId: "toolchain",
    title: "CUDA Installation Guide for Linux",
    url: "https://docs.nvidia.com/cuda/cuda-installation-guide-linux/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cuda-guide",
    moduleId: "architecture",
    title: "CUDA Programming Guide",
    url: "https://docs.nvidia.com/cuda/cuda-programming-guide/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cuda-tile",
    moduleId: "architecture",
    title: "CUDA 13.1 and CUDA Tile",
    url: "https://developer.nvidia.com/blog/nvidia-cuda-13-1-powers-next-gen-gpu-programming-with-nvidia-cuda-tile-and-performance-gains/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cuda-tile-nvcc-13-3",
    moduleId: "architecture",
    title: "NVIDIA CUDA Compiler Driver 13.3 — Tile Compilation",
    url: "https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutile-python-1-5-release",
    moduleId: "architecture",
    title: "cuTile Python 1.5.0 Release Notes",
    url: "https://docs.nvidia.com/cuda/cutile-python/generated/release_notes.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cuda-memory",
    moduleId: "memory",
    title: "CUDA Programming Guide: Memory",
    url: "https://docs.nvidia.com/cuda/cuda-programming-guide/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "pytorch-custom-ops",
    moduleId: "triton",
    title: "PyTorch Custom Operators",
    url: "https://docs.pytorch.org/tutorials/advanced/custom_ops_landing_page.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "pytorch-triton-integration",
    moduleId: "triton",
    title: "Using User-Defined Triton Kernels with torch.compile",
    url: "https://docs.pytorch.org/tutorials/recipes/torch_compile_user_defined_triton_kernel_tutorial.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "triton-gluon",
    moduleId: "triton",
    title: "Introduction to Gluon",
    url: "https://triton-lang.org/main/getting-started/tutorials/gluon/intro.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "triton-tutorials",
    moduleId: "operators",
    title: "Triton Tutorials",
    url: "https://triton-lang.org/main/getting-started/tutorials/index.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "triton-operator-tutorials",
    moduleId: "operators",
    title: "Triton Operator Tutorials",
    url: "https://triton-lang.org/main/getting-started/tutorials/index.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "triton-block-scaled",
    moduleId: "operators",
    title: "Block Scaled Matrix Multiplication",
    url: "https://triton-lang.org/main/getting-started/tutorials/10-block-scaled-matmul.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-paged-attention-design",
    moduleId: "operators",
    title: "vLLM Paged Attention Design",
    url: "https://docs.vllm.ai/en/latest/design/paged_attention/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "pytorch-sdpa-gqa",
    moduleId: "operators",
    title: "PyTorch scaled_dot_product_attention",
    url: "https://docs.pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "compute-sanitizer",
    moduleId: "correctness",
    title: "Compute Sanitizer",
    url: "https://docs.nvidia.com/compute-sanitizer/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "compute-sanitizer-release",
    moduleId: "correctness",
    title: "Compute Sanitizer Release Notes",
    url: "https://docs.nvidia.com/compute-sanitizer/ReleaseNotes/index.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nsight-release-notes",
    moduleId: "profiling",
    title: "Nsight Compute Release Notes",
    url: "https://docs.nvidia.com/nsight-compute/ReleaseNotes/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nsight-compute-2026-release",
    moduleId: "profiling",
    title: "Nsight Compute Release Notes",
    url: "https://docs.nvidia.com/nsight-compute/ReleaseNotes/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-changelog",
    moduleId: "cutlass",
    title: "CUTLASS Changelog",
    url: "https://docs.nvidia.com/cutlass/latest/CHANGELOG.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-overview-4",
    moduleId: "cutlass",
    title: "CUTLASS 4 Overview",
    url: "https://docs.nvidia.com/cutlass/latest/overview.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-cpp-templates",
    moduleId: "cutlass",
    title: "CUTLASS 3.x GEMM API",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/gemm_api_3x.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-cute-dsl",
    moduleId: "cutlass",
    title: "CuTe DSL",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/pythonDSL/cute_dsl.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "cutlass-legacy-generator",
    moduleId: "cutlass",
    title: "CUTLASS Code Organization",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/code_organization.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-blackwell-sm100",
    moduleId: "cutlass",
    title: "CUTLASS Blackwell SM100 GEMMs",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/blackwell_functionality.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-grouped-scheduler",
    moduleId: "cutlass",
    title: "CUTLASS Grouped Kernel Schedulers",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/grouped_scheduler.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-blackwell-clc",
    moduleId: "cutlass",
    title: "CUTLASS Blackwell Cluster Launch Control",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/blackwell_cluster_launch_control.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-rubin-sm107",
    moduleId: "cutlass",
    title: "CUTLASS Rubin SM107 Changelog",
    url: "https://docs.nvidia.com/cutlass/latest/CHANGELOG.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "vllm-stable",
    moduleId: "inference",
    title: "vLLM Stable Documentation",
    url: "https://docs.vllm.ai/en/stable/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-disaggregated-encoder",
    moduleId: "inference",
    title: "Disaggregated Encoder",
    url: "https://docs.vllm.ai/en/latest/examples/disaggregated/disaggregated_encoder/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-cuda-graph-modes",
    moduleId: "inference",
    title: "vLLM CUDA Graphs",
    url: "https://docs.vllm.ai/en/stable/design/cuda_graphs/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "hip-graphs-runtime",
    moduleId: "inference",
    title: "HIP Graphs Runtime API",
    url: "https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/hip_runtime_api/hipgraph.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "amd-hip-graphs",
    moduleId: "inference",
    title: "AMD HIP Graphs Runtime API",
    url: "https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/hip_runtime_api/hipgraph.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-quantization-hardware",
    moduleId: "inference",
    title: "vLLM Quantization Supported Hardware",
    url: "https://docs.vllm.ai/en/stable/features/quantization/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-speculative-acceptance",
    moduleId: "inference",
    title: "vLLM Per-Request Acceptance Metrics",
    url: "https://docs.vllm.ai/en/latest/features/speculative_decoding/acceptance_metrics/",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "vllm-expert-parallel",
    moduleId: "inference",
    title: "vLLM Expert Parallel Deployment",
    url: "https://docs.vllm.ai/en/latest/serving/expert_parallel_deployment/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-context-parallel",
    moduleId: "inference",
    title: "vLLM Context Parallel Deployment",
    url: "https://docs.vllm.ai/en/latest/serving/context_parallel_deployment/",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "vllm-online-quantization",
    moduleId: "inference",
    title: "vLLM Online Quantization",
    url: "https://docs.vllm.ai/en/latest/features/quantization/online/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-inference-formats",
    moduleId: "inference",
    title: "CUTLASS Blackwell Block-Scaled Formats",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/blackwell_functionality.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-release-notes",
    moduleId: "multigpu",
    title: "NCCL Release Notes",
    url: "https://docs.nvidia.com/deeplearning/nccl/release-notes/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-topology-detection",
    moduleId: "multigpu",
    title: "NCCL Topology Detection",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting/gpu_troubleshooting.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-pcie-p2p",
    moduleId: "multigpu",
    title: "NCCL PCIe Peer-to-Peer Check",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting/gpu_troubleshooting.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-nvlink-p2p",
    moduleId: "multigpu",
    title: "NCCL NVLink Peer-to-Peer Check",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting/gpu_troubleshooting.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-nvswitch-topology",
    moduleId: "multigpu",
    title: "NVIDIA Multi-Node NVLink Systems",
    url: "https://docs.nvidia.com/multi-node-nvlink-systems/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-gpudirect-rdma",
    moduleId: "multigpu",
    title: "NVIDIA GPUDirect RDMA",
    url: "https://docs.nvidia.com/cuda/gpudirect-rdma/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-device-api-experimental",
    moduleId: "multigpu",
    title: "NCCL 2.28.3 Device API Release Notes",
    url: "https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-28-3.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "nccl-device-api-fusion",
    moduleId: "multigpu",
    title: "NCCL Device API",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/device.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-device-lsa-multimem",
    moduleId: "multigpu",
    title: "NCCL 2.31.2 Device API — LSA and Multimem Compatibility",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/deviceapi.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-device-gin",
    moduleId: "multigpu",
    title: "NCCL 2.31.2 Device API — GIN Recompile Boundary",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/deviceapi.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-device-rust-bindings",
    moduleId: "multigpu",
    title: "NCCL 2.31.2 Experimental Rust Device API Bindings",
    url: "https://docs.nvidia.com/deeplearning/nccl/archives/nccl_2312/release-notes/rel_2-31-2.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "nvshmem-symmetric-memory",
    moduleId: "multigpu",
    title: "NVIDIA NVSHMEM Symmetric Memory",
    url: "https://docs.nvidia.com/nvshmem/api/latest/using.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "nccl-cuda-streams",
    moduleId: "multigpu",
    title: "NCCL CUDA Stream Semantics",
    url: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/streams.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "vllm-parallelism-scaling",
    moduleId: "multigpu",
    title: "vLLM Parallelism and Scaling",
    url: "https://docs.vllm.ai/en/stable/serving/parallelism_scaling/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "rocm-release-notes",
    moduleId: "systems",
    title: "ROCm Release Notes",
    url: "https://rocm.docs.amd.com/en/develop/about/release-notes.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "rocm-10-core",
    moduleId: "systems",
    title: "ROCm Core SDK 10.0.0 Release Notes",
    url: "https://rocm.docs.amd.com/en/develop/about/release-notes.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "rocprofiler-sdk-rocm10",
    moduleId: "systems",
    title: "ROCprofiler-SDK in ROCm 10",
    url: "https://rocm.docs.amd.com/en/develop/about/release-notes.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "hip-programming-rocm10",
    moduleId: "systems",
    title: "AMD GPU Programming on ROCm",
    url: "https://rocm.docs.amd.com/en/develop/reference/hip-programming.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "mlir-dialect-conversion",
    moduleId: "systems",
    title: "MLIR Dialect Conversion",
    url: "https://mlir.llvm.org/docs/DialectConversion/",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cuda-tile-ir",
    moduleId: "systems",
    title: "CUDA Tile IR",
    url: "https://docs.nvidia.com/cuda/tile-ir/main/sections/introduction.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutile-tileir",
    moduleId: "systems",
    title: "cuTile Python Quickstart",
    url: "https://docs.nvidia.com/cuda/cutile-python/quickstart.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cutlass-kernel-library",
    moduleId: "systems",
    title: "CUTLASS C++ Functionality",
    url: "https://docs.nvidia.com/cutlass/latest/media/docs/cpp/functionality.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "cute-dsl-stack",
    moduleId: "systems",
    title: "CUTLASS CuTe DSL Overview",
    url: "https://docs.nvidia.com/cutlass/latest/overview.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "tensorrt-how-it-works",
    moduleId: "systems",
    title: "How TensorRT Works",
    url: "https://docs.nvidia.com/deeplearning/tensorrt/latest/architecture/how-trt-works.html",
    verifiedAt: "2026-09-04",
    maturity: "current",
  },
  {
    id: "triton-tileir-incubator",
    moduleId: "systems",
    title: "Triton-to-Tile-IR Incubator",
    url: "https://github.com/triton-lang/Triton-to-tile-IR",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
  {
    id: "systems-rubin-sm107",
    moduleId: "systems",
    title: "CUTLASS Rubin SM107 Changelog",
    url: "https://docs.nvidia.com/cutlass/latest/CHANGELOG.html",
    verifiedAt: "2026-09-04",
    maturity: "preview",
  },
] as const satisfies readonly CurriculumSource[];

export function getSourcesForModule(id: ModuleId): readonly CurriculumSource[] {
  return curriculumSources.filter((source) => source.moduleId === id);
}
